# Generated by Django 4.0.5 on 2022-06-06 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_id'),
        ('event', '0003_remove_event_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medal', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='user.user')),
            ],
        ),
    ]
