# Generated by Django 4.0.5 on 2022-06-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_medal'),
        ('user', '0002_alter_user_id'),
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='event.event'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='user.user'),
        ),
    ]
