# Generated by Django 4.0.5 on 2022-06-05 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('localization', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('medal', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.game')),
                ('localization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localization', to='localization.localization')),
                ('users', models.ManyToManyField(null=True, related_name='users', to='user.user')),
            ],
        ),
    ]
