# Generated by Django 4.0.5 on 2022-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='medal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
