# Generated by Django 4.0.5 on 2022-06-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
        ('measure', '0002_alter_measure_heigth_alter_measure_wheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='user.user'),
        ),
    ]
