# Generated by Django 4.0.5 on 2022-06-05 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.BigIntegerField()),
                ('season', models.CharField(max_length=255)),
                ('teams', models.ManyToManyField(null=True, related_name='teams', to='team.team')),
            ],
        ),
    ]
