# Generated by Django 4.0.5 on 2022-06-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(null=True, related_name='games', to='team.team'),
        ),
    ]
